version: "2"
services:
  front:
    build: ../myApp/
    ports:
      - "3000:3000"
    environment:
      REACT_APP_LOCAL_SERVER: http://localhost:4242
      REACT_APP_SERVER: http://localhost:5000

  local:
    build: ../local/
    ports:
      - "4242:4242"
    links:
      - "server"
    environment:
      SERVER: http://server:5000

  server:
    build: ../server/
    ports:
      - "5000:5000"
